name: Deploy to Kemono Cafe

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm install
    - run: npm run build

    - name: Sync to KC Server
      env:
        dest: '${{secrets.PRODUCTION_IP}}:/var/www/html/wp-content/themes/test-theme/'
      run: |
        echo "${{secrets.DEPLOYMENT_SSH_PRIVATE_KEY}}" > deploy_key
        chmod 600 ./deploy_key
        rsync -chav --delete \
          --rsync-path="sudo rsync" \
          -e 'ssh -p ${{secrets.PRODUCTION_PORT}} -i ./deploy_key -o StrictHostKeyChecking=no' \
          --exclude /deploy_key \
          --exclude /.git/ \
          --exclude /.github/ \
          --exclude /node_modules/ \
          ./ ${{secrets.PRODUCTION_USER}}@${{env.dest}}
